spring.application.name=studentmanagement

spring.datasource.url=jdbc:mysql://localhost:3307/pavan
spring.datasource.username=root
spring.datasource.password=root

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
